### ISSUE TITLE
Chapter 2 - Installing WSL

### ISSUE THREAD

**Issue by ViniciusSouza** [PacktPublishing/WSL-2-Tips-Tricks-and-Techniques#3]
Hi @stuartleeks  I'm setting up WSL in a new machine and during the process I have found a important step missing at your instructions on installing WSL which is **enabling virtualization at the bios**.  

I complete forgot about it when setting up the bios and I noticed it when I was trying to launch my distro and faced this message.

```
Installing, this may take a few minutes...
WslRegisterDistribution failed with error: 0x80370102
Error: 0x80370102 The virtual machine could not be started because a required feature is not installed.

Press any key to continue...
```

This is when I did realize that I haven't enabled the Virtualization at the bios.

**Comment by stuartleeks** [comment]
Hi @ViniciusSouza - good point, I'll make a note for any future revision. Thanks for flagging!
