### ISSUE TITLE
Chaper4 (WebApp)Should I copy these files inside the Ubuntu distro?

### ISSUE THREAD

**Issue by jhorgint** [PacktPublishing/WSL-2-Tips-Tricks-and-Techniques#4]
in order to run the Web-App Chapter-4, should I copy these files inside Ubuntu? or it's unnecessary.

**Comment by stuartleeks** [comment]
Hi @jhorgint,

The `.ps1` file is example PowerShell commands from the chapter and designed to be run from PowerShell in Windows. The `web-app` folder is intended to be run from WSL.

Hope that helps!
Stuart

**Comment by jhorgint** [comment]
Thanks Stuart. I have finally gotten it running. 
using PowerShell and this command "Bash run.sh"
PS C:\web-app> Bash run.sh
