### ISSUE TITLE
Configuring Windows Terminal Page 40

### ISSUE THREAD

**Issue by carltyndall** [PacktPublishing/WSL-2-Tips-Tricks-and-Techniques#5]
Configuring Windows Terminal in Windows Terminal Version: 1.8.1521.0 behaves differently than in the book page 40.

"The settings for Windows Terminal are all stored in a JSON file tucked away in your
Windows profile. To access the settings, you can click on the down arrow to select a
profile to launch and then choose Settings or you can use the **Ctrl + ,** keyboard shortcut.
Windows Terminal will open settings.json in the default editor for JSON files for
your system."
**CTRL+,** now opens a settings tab.
**CTRL+ALT+,** will open a default settings file that is autogenerated.
**CTRL+SHift+,** will open the settings file.

**Comment by stuartleeks** [comment]
Hi @Carl-Ty  - thanks for raising the issue. As you noted, the behaviour of Windows Terminal has changed slightly since the book was written. I'm glad you managed to find the new shortcut keys!
