### ISSUE TITLE
Setting tab titles from the command line

### ISSUE THREAD

**Issue by carltyndall** [PacktPublishing/WSL-2-Tips-Tricks-and-Techniques#6]
Page 89: 
From the command line:
wt.exe -p "PowerShell" --title "This one is PowerShell";new-tab -p "Ubuntu-20.04" --title "WSL here!"
From Powershell:
wt.exe -p "PowerShell" --title "This one is PowerShell"`;new-tab -p "Ubuntu-20.04" --title "WSL here!"
Do not appear to change the title of the Ubuntu tab.

Per [Rename tab title not working for WSL and Bash #5333 Closed](https://github.com/microsoft/terminal/issues/5333)  "Turn on the suppressApplicationTitle option. The "tab title" is a recommendation, and the application can delete it if it wants to. Bash usually does. **supressApplicationTitle** overrides bash."

The following change in settings.json worked for me:
```
{
  "guid": "{07b52e3e-de2c-5db4-bd2d-ba144ed6c273}",
  "hidden": false,
  "name": "Ubuntu-20.04",
  "source": "Windows.Terminal.Wsl",
  "suppressApplicationTitle": true
},
```

**Comment by stuartleeks** [comment]
Thanks, @Carl-Ty! It looks like this behaviour has changed since I tested the scripts in the book and will be one to revisit if there's another edition 😄

**Comment by sprototles** [comment]
So what command executed in Ubuntu will change Ubuntu terminal title ? I am asking because i have like 10 tabs open and all of them starts like: _thisuser@DESKTOP-1A2B3C4D/..._ and rest is hidden. Renaming tabs manually works but i would rather automate that

I tried following options, none of them worked:

```
echo -ne "\033]0;foo\007"
bash -c 'echo -ne "\033]0;foo\007"'
```

Thx

**Comment by stuartleeks** [comment]
I'd suggest testing the command here: https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title#set-the-shells-title

Also, if you're using Windows Terminal, [check that you haven't got `suppressApplicationTitle` set](https://docs.microsoft.com/en-us/windows/terminal/tutorials/tab-title#use-the-suppressapplicationtitle-setting).

**Comment by Kwaadpepper** [comment]
I just set "suppressApplicationTitle": false,
And used https://github.com/trystan2k/zsh-tab-title
With windows terminal and OhMyZSH this works flawlessly
